# Generated by Django 2.2.5 on 2020-01-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191231_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('audio', models.FileField(upload_to='music/')),
                ('image', models.ImageField(upload_to='music/image/')),
            ],
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
