# Generated by Django 2.2.5 on 2020-01-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200101_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image',
            field=models.ImageField(upload_to='music/'),
        ),
    ]
