# Generated by Django 2.2.5 on 2020-01-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200101_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='audio',
        ),
    ]
