# Generated by Django 2.2.5 on 2020-01-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200101_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='song',
            field=models.FileField(default='', upload_to='music/images/audio'),
        ),
    ]
