# Generated by Django 2.2.5 on 2020-01-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_audio_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='song',
            field=models.FileField(default='', upload_to='music/audio'),
        ),
    ]
