# Generated by Django 2.2.5 on 2020-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200103_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('image', models.ImageField(default='', upload_to='music/images')),
                ('song', models.FileField(default='', upload_to='music/audio')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='audio',
        ),
    ]
