# Generated by Django 2.2.5 on 2020-01-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200103_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='key',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
