# Generated by Django 2.2.5 on 2020-01-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_detail_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='provideInnerHtml',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
