# Generated by Django 2.2.5 on 2020-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_detail_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='audio_class',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
