# Generated by Django 2.2.5 on 2020-01-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_detail_audio_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='audio_class',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='key',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='number',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='provideInnerHtml',
        ),
    ]
