# Generated by Django 2.2.5 on 2020-01-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20200104_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='key',
            field=models.CharField(default=0, max_length=90),
        ),
    ]
