# Generated by Django 2.2.5 on 2020-01-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_detail_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='lyrics',
            field=models.CharField(default=0, max_length=1000000),
        ),
    ]
