# Generated by Django 2.2.5 on 2020-01-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_detail_lyrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='detail',
            name='key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
