# Generated by Django 2.2.5 on 2020-01-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20200104_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('image', models.ImageField(default='', upload_to='music/images')),
                ('song', models.FileField(default='', upload_to='music/audio')),
                ('text', models.CharField(max_length=10000)),
                ('lyrics', models.CharField(default=0, max_length=1000000)),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
